"""Canonical envelopes generated by the real connector.

Gateway tests should import these objects instead of hand-building envelopes.
That keeps content inspection, normalization, hashes, spans, and child lineage
on the same seam used by the demo.
"""

from __future__ import annotations

from pathlib import Path

from connector.ingest import ingest, ingest_attested_claim
from schemas import AttestedClaim, SourceEnvelope


_ROOT = Path(__file__).resolve().parent
_PORTAL_AUTH = {
    "assurance": "phishing_resistant",
    "system_signed": True,
    "user_attested": True,
}


def _read(name: str) -> bytes:
    return (_ROOT / name).read_bytes()


def _invoice(name: str) -> SourceEnvelope:
    envelopes = ingest(
        _read(name),
        "application/pdf",
        "inbound_email",
        "vendor_123",
        "none",
    )
    if len(envelopes) != 1:
        raise RuntimeError(f"{name} unexpectedly produced {len(envelopes)} envelopes")
    return envelopes[0]


CLEAN_INVOICE_ENVELOPE = _invoice("invoice_clean.pdf")
POISONED_INVOICE_ENVELOPE = _invoice("invoice_poisoned.pdf")
QR_AMOUNT_INVOICE_ENVELOPE = _invoice("invoice_qr_amount.pdf")

FORWARDED_EMAIL_ENVELOPES = tuple(
    ingest(
        _read("email_forwarded.eml"),
        "message/rfc822",
        "inbound_email",
        "finance_admin_456",
        "mfa",
    )
)
if len(FORWARDED_EMAIL_ENVELOPES) != 2:
    raise RuntimeError(
        "email_forwarded.eml must produce an email envelope and an attachment envelope"
    )

_vendor_change_raw = _read("vendor_change_form.json")
_vendor_change_envelopes = ingest(
    _vendor_change_raw,
    "application/json",
    "admin_portal",
    "finance_admin_456",
    _PORTAL_AUTH,
)
if len(_vendor_change_envelopes) != 1:
    raise RuntimeError("vendor_change_form.json must produce exactly one envelope")
VENDOR_CHANGE_FORM_ENVELOPE = _vendor_change_envelopes[0]
VENDOR_CHANGE_CLAIM: AttestedClaim = ingest_attested_claim(
    _vendor_change_raw,
    "admin_portal",
    "finance_admin_456",
    _PORTAL_AUTH,
)

FIXTURE_ENVELOPES: dict[str, tuple[SourceEnvelope, ...]] = {
    "invoice_clean.pdf": (CLEAN_INVOICE_ENVELOPE,),
    "invoice_poisoned.pdf": (POISONED_INVOICE_ENVELOPE,),
    "email_forwarded.eml": FORWARDED_EMAIL_ENVELOPES,
    "vendor_change_form.json": (VENDOR_CHANGE_FORM_ENVELOPE,),
    "invoice_qr_amount.pdf": (QR_AMOUNT_INVOICE_ENVELOPE,),
}
